export const fruits = [{
    id: 1,
    name: "Apple",
    color: "Red",
    weight: 150, // in grams
    price: 1.2, // in USD
    origin: "USA",
    isTropical: false,
    nutrients: {
      calories: 52,
      sugar: "10g",
      fiber: "2.4g",
      vitaminC: "8% DV",
    },
  },
  {
    id: 2,
    name: "Orange",
    color: "Orange",
    weight: 200,
    price: 0.8,
    origin: "Spain",
    isTropical: true,
    nutrients: {
      calories: 47,
      sugar: "9g",
      fiber: "2.3g",
      vitaminC: "89% DV",
    },
  },
  {
    id: 3,
    name: "Banana",
    color: "Yellow",
    weight: 120,
    price: 0.5,
    origin: "Ecuador",
    isTropical: true,
    nutrients: {
      calories: 96,
      sugar: "14g",
      fiber: "2.6g",
      vitaminC: "15% DV",
    },
  },
  {
    id: 4,
    name: "Coconut",
    color: "Brown",
    weight: 1000,
    price: 3.5,
    origin: "Thailand",
    isTropical: true,
    nutrients: {
      calories: 354,
      sugar: "6.2g",
      fiber: "9g",
      vitaminC: "4% DV",
    },
  },
  {
    id: 5,
    name: "Pineapple",
    color: "Yellow",
    weight: 900,
    price: 2.5,
    origin: "Philippines",
    isTropical: true,
    nutrients: {
      calories: 50,
      sugar: "10g",
      fiber: "1.4g",
      vitaminC: "79% DV",
    },
  },
];